version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ./siq_packages:/home/node/app/siq_packages
    ports:
      - 4000:3000
      - 9229:9229
    depends_on:
      - db
    env_file:
      - .env

volumes:
  database:
