version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  api:
    build:
      dockerfile: ./docker/debug/Dockerfile
      context: ../
    restart: always
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  database:
